// cspell:ignore Botswanan,Rican Colón,Verdean,Djiboutian,Kazakhstani,Ariary,Myanma,Nuevo,Paʻanga,Bolívar,BCEAO,BEAC,FCFA

export const currencies = [
  { name: 'Euro', symbol: '€', code: 'EUR' },
  { name: 'Thai Baht', symbol: '฿', code: 'THB' },
  { name: 'US Dollar', symbol: '$', code: 'USD' },
  { name: 'Canadian Dollar', symbol: 'CA$', code: 'CAD' },
  { name: 'United Arab Emirates Dirham', symbol: 'AED', code: 'AED' },
  { name: 'Afghan Afghani', symbol: 'Af', code: 'AFN' },
  { name: 'Albanian Lek', symbol: 'ALL', code: 'ALL' },
  { name: 'Armenian Dram', symbol: 'AMD', code: 'AMD' },
  { name: 'Argentine Peso', symbol: 'AR$', code: 'ARS' },
  { name: 'Australian Dollar', symbol: 'AU$', code: 'AUD' },
  { name: 'Azerbaijani Manat', symbol: 'man.', code: 'AZN' },
  { name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', code: 'BAM' },
  { name: 'Bangladeshi Taka', symbol: 'Tk', code: 'BDT' },
  { name: 'Bulgarian Lev', symbol: 'BGN', code: 'BGN' },
  { name: 'Bahraini Dinar', symbol: 'BD', code: 'BHD' },
  { name: 'Burundian Franc', symbol: 'FBu', code: 'BIF' },
  { name: 'Brunei Dollar', symbol: 'BN$', code: 'BND' },
  { name: 'Bolivian Boliviano', symbol: 'Bs', code: 'BOB' },
  { name: 'Brazilian Real', symbol: 'R$', code: 'BRL' },
  { name: 'Botswanan Pula', symbol: 'BWP', code: 'BWP' },
  { name: 'Belarusian Ruble', symbol: 'Br', code: 'BYN' },
  { name: 'Belize Dollar', symbol: 'BZ$', code: 'BZD' },
  { name: 'Congolese Franc', symbol: 'CDF', code: 'CDF' },
  { name: 'Swiss Franc', symbol: 'CHF', code: 'CHF' },
  { name: 'Chilean Peso', symbol: 'CL$', code: 'CLP' },
  { name: 'Chinese Yuan', symbol: 'CN¥', code: 'CNY' },
  { name: 'Colombian Peso', symbol: 'CO$', code: 'COP' },
  { name: 'Costa Rican Colón', symbol: '₡', code: 'CRC' },
  { name: 'Cape Verdean Escudo', symbol: 'CV$', code: 'CVE' },
  { name: 'Czech Republic Koruna', symbol: 'Kč', code: 'CZK' },
  { name: 'Djiboutian Franc', symbol: 'Fdj', code: 'DJF' },
  { name: 'Danish Krone', symbol: 'Dkr', code: 'DKK' },
  { name: 'Dominican Peso', symbol: 'RD$', code: 'DOP' },
  { name: 'Algerian Dinar', symbol: 'DA', code: 'DZD' },
  { name: 'Estonian Kroon', symbol: 'Ekr', code: 'EEK' },
  { name: 'Egyptian Pound', symbol: 'EGP', code: 'EGP' },
  { name: 'Eritrean Nakfa', symbol: 'Nfk', code: 'ERN' },
  { name: 'Ethiopian Birr', symbol: 'EBr', code: 'ETB' },
  { name: 'British Pound Sterling', symbol: '£', code: 'GBP' },
  { name: 'Georgian Lari', symbol: 'GEL', code: 'GEL' },
  { name: 'Ghanaian Cedi', symbol: 'GH₵', code: 'GHS' },
  { name: 'Guinean Franc', symbol: 'FG', code: 'GNF' },
  { name: 'Guatemalan Quetzal', symbol: 'GTQ', code: 'GTQ' },
  { name: 'Hong Kong Dollar', symbol: 'HK$', code: 'HKD' },
  { name: 'Honduran Lempira', symbol: 'HNL', code: 'HNL' },
  { name: 'Croatian Kuna', symbol: 'kn', code: 'HRK' },
  { name: 'Hungarian Forint', symbol: 'Ft', code: 'HUF' },
  { name: 'Indonesian Rupiah', symbol: 'Rp', code: 'IDR' },
  { name: 'Israeli New Sheqel', symbol: '₪', code: 'ILS' },
  { name: 'Indian Rupee', symbol: 'Rs', code: 'INR' },
  { name: 'Iraqi Dinar', symbol: 'IQD', code: 'IQD' },
  { name: 'Iranian Rial', symbol: 'IRR', code: 'IRR' },
  { name: 'Icelandic Króna', symbol: 'Ikr', code: 'ISK' },
  { name: 'Jamaican Dollar', symbol: 'J$', code: 'JMD' },
  { name: 'Jordanian Dinar', symbol: 'JD', code: 'JOD' },
  { name: 'Japanese Yen', symbol: '¥', code: 'JPY' },
  { name: 'Kenyan Shilling', symbol: 'Ksh', code: 'KES' },
  { name: 'Cambodian Riel', symbol: 'KHR', code: 'KHR' },
  { name: 'Comorian Franc', symbol: 'CF', code: 'KMF' },
  { name: 'South Korean Won', symbol: '₩', code: 'KRW' },
  { name: 'Kuwaiti Dinar', symbol: 'KD', code: 'KWD' },
  { name: 'Kazakhstani Tenge', symbol: 'KZT', code: 'KZT' },
  { name: 'Lebanese Pound', symbol: 'LB£', code: 'LBP' },
  { name: 'Sri Lankan Rupee', symbol: 'SLRs', code: 'LKR' },
  { name: 'Lithuanian Litas', symbol: 'Lt', code: 'LTL' },
  { name: 'Latvian Lats', symbol: 'Ls', code: 'LVL' },
  { name: 'Libyan Dinar', symbol: 'LD', code: 'LYD' },
  { name: 'Moroccan Dirham', symbol: 'MAD', code: 'MAD' },
  { name: 'Moldovan Leu', symbol: 'MDL', code: 'MDL' },
  { name: 'Malagasy Ariary', symbol: 'MGA', code: 'MGA' },
  { name: 'Macedonian Denar', symbol: 'MKD', code: 'MKD' },
  { name: 'Myanma Kyat', symbol: 'MMK', code: 'MMK' },
  { name: 'Macanese Pataca', symbol: 'MOP$', code: 'MOP' },
  { name: 'Mauritian Rupee', symbol: 'MURs', code: 'MUR' },
  { name: 'Mexican Peso', symbol: 'MX$', code: 'MXN' },
  { name: 'Malaysian Ringgit', symbol: 'RM', code: 'MYR' },
  { name: 'Mozambican Metical', symbol: 'MTn', code: 'MZN' },
  { name: 'Namibian Dollar', symbol: 'N$', code: 'NAD' },
  { name: 'Nigerian Naira', symbol: '₦', code: 'NGN' },
  { name: 'Nicaraguan Córdoba', symbol: 'C$', code: 'NIO' },
  { name: 'Norwegian Krone', symbol: 'Nkr', code: 'NOK' },
  { name: 'Nepalese Rupee', symbol: 'NPRs', code: 'NPR' },
  { name: 'New Zealand Dollar', symbol: 'NZ$', code: 'NZD' },
  { name: 'Omani Rial', symbol: 'OMR', code: 'OMR' },
  { name: 'Panamanian Balboa', symbol: 'B/.', code: 'PAB' },
  { name: 'Peruvian Nuevo Sol', symbol: 'S/.', code: 'PEN' },
  { name: 'Philippine Peso', symbol: '₱', code: 'PHP' },
  { name: 'Pakistani Rupee', symbol: 'PKRs', code: 'PKR' },
  { name: 'Polish Zloty', symbol: 'zł', code: 'PLN' },
  { name: 'Paraguayan Guarani', symbol: '₲', code: 'PYG' },
  { name: 'Qatari Rial', symbol: 'QR', code: 'QAR' },
  { name: 'Romanian Leu', symbol: 'RON', code: 'RON' },
  { name: 'Serbian Dinar', symbol: 'din.', code: 'RSD' },
  { name: 'Russian Ruble', symbol: 'RUB', code: 'RUB' },
  { name: 'Rwandan Franc', symbol: 'RWF', code: 'RWF' },
  { name: 'Saudi Riyal', symbol: 'SR', code: 'SAR' },
  { name: 'Sudanese Pound', symbol: 'SDG', code: 'SDG' },
  { name: 'Swedish Krona', symbol: 'Skr', code: 'SEK' },
  { name: 'Singapore Dollar', symbol: 'S$', code: 'SGD' },
  { name: 'Somali Shilling', symbol: 'Ssh', code: 'SOS' },
  { name: 'Syrian Pound', symbol: 'SY£', code: 'SYP' },
  { name: 'Tunisian Dinar', symbol: 'DT', code: 'TND' },
  { name: 'Tongan Paʻanga', symbol: 'T$', code: 'TOP' },
  { name: 'Turkish Lira', symbol: 'TL', code: 'TRY' },
  { name: 'Trinidad and Tobago Dollar', symbol: 'TT$', code: 'TTD' },
  { name: 'New Taiwan Dollar', symbol: 'NT$', code: 'TWD' },
  { name: 'Tanzanian Shilling', symbol: 'TSh', code: 'TZS' },
  { name: 'Ukrainian Hryvnia', symbol: '₴', code: 'UAH' },
  { name: 'Ugandan Shilling', symbol: 'USh', code: 'UGX' },
  { name: 'Uruguayan Peso', symbol: '$U', code: 'UYU' },
  { name: 'Uzbekistan Som', symbol: 'UZS', code: 'UZS' },
  { name: 'Venezuelan Bolívar', symbol: 'Bs.F.', code: 'VEF' },
  { name: 'Vietnamese Dong', symbol: '₫', code: 'VND' },
  { name: 'CFA Franc BEAC', symbol: 'FCFA', code: 'XAF' },
  { name: 'CFA Franc BCEAO', symbol: 'CFA', code: 'XOF' },
  { name: 'Yemeni Rial', symbol: 'YR', code: 'YER' },
  { name: 'South African Rand', symbol: 'R', code: 'ZAR' },
  { name: 'Zambian Kwacha', symbol: 'ZK', code: 'ZMK' },
  { name: 'Zimbabwean Dollar', symbol: 'ZWL$', code: 'ZWL' },
]
