services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: