[env]
_.path = ["./node_modules/.bin"]

[settings]
quiet = true

[tools]
node = "24"
pnpm = "latest"

[tasks."update:mise"]
sources = ["mise.toml", "mise.*.toml"]
run = "mise upgrade --quiet"

[tasks."update:app"]
depends = ["update:mise"]
sources = ["package.json", "pnpm-lock.yaml"]
outputs = ["node_modules/.modules.yaml"]
run = "pnpm install -y --loglevel warn && touch node_modules/.modules.yaml"

[tasks.update]
depends = ["update:*"]

[tasks."log:versions"]
run = '''
    printf "\033[32m[+] dev tools\033[0m\n"
    printf "    \033[32m- %s\033[0m %7s\n" \
        "node" "$(node -v | sed 's/v//')" \
        "pnpm" "$(pnpm -v)"
    '''

[hooks]
enter = [{ task = "update" }, { task = "log:versions" }]
